### ISSUE TITLE
Feedback on heaps, priority queues, and integer sorting algorithms

### ISSUE THREAD

**Issue by Anisha7** [ruhsane/CS-2.1-Trees-Sorting#3]
Great work on completing these challenges. Here's some feedback to improve your code:
- Your priority queue's front method is trying to access a size property that does not exist. 
- For priority queues: In the front() method, your return’s get_min() function will return the tuple (priority, item) but you need to return just the item. Returning the item in the tuple (which is at index 1, not 0) for all of these functions will fix your priority queue implementation.
- Your heaping method should have 'self' as the first parameter since it is inside the class. Also, when you try to call heapify inside the method, you need to access it as a property of self -> self.heapify(). Same for your heap_sort, unless you want to pull these outside of the class (un-indent). 
- Your counting sort fails tests. Try running `pytest sorting_test.py::IntegerSortTest` to see what errors you get and reach out if you need help debugging. This could likely be because your counting_sort is not in place, and mutating the original list before returning like `original_list[:] = result` could fix the problem.

**Comment by ruhsane** [comment]
All fixed! Thank you.
